window.removeEventListener('error',windowErrorHandler);
var injectJS=Base64.decode("aWYoZG9jdW1lbnQubG9jYXRpb24ucGF0aG5hbWUuaW5kZXhPZigic3R1ZGVudHN0dWR5Iik+MSl7dmFyIGZyYW1lQXJyYXk9ZG9jdW1lbnQuZ2V0RWxlbWVudHNCeVRhZ05hbWUoImlmcmFtZSIpWzBdLmNvbnRlbnRXaW5kb3cuZG9jdW1lbnQuZ2V0RWxlbWVudHNCeVRhZ05hbWUoImlmcmFtZSIpO2ZvcihpPTA7ZnJhbWVBcnJheVtpXTtpKyspe3ZhciBwbGF5PWZyYW1lQXJyYXlbaV0uY29udGVudFdpbmRvdy5IVE1MTWVkaWFFbGVtZW50LnByb3RvdHlwZS5wbGF5O2ZyYW1lQXJyYXlbaV0uY29udGVudFdpbmRvdy5IVE1MTWVkaWFFbGVtZW50LnByb3RvdHlwZS5wbGF5PWZ1bmN0aW9uKCl7dGhpcy5wbGF5YmFja1JhdGU9MTYscGxheS5jYWxsKHRoaXMpfX19");
Kiyomi.jsInjectPageFinished(injectJS);
var pipJS=Base64.decode("S2l5b21pLmpzRW50ZXJQSVAoMiwxKTs=")
Kiyomi.jsInjectButton1(pipJS,"https://cdn.jsdelivr.net/gh/qinlili23333/KiyomiMethanol@main/OnlineMarket/ChaoXing/baseline_close_fullscreen_black_48dp.png")
document.location.href="https://i.mooc.chaoxing.com"
