window.removeEventListener('error',windowErrorHandler);
var injectJS=Base64.decode("amF2YXNjcmlwdDppZihkb2N1bWVudC5sb2NhdGlvbi5wYXRobmFtZS5pbmRleE9mKCJzdHVkZW50c3R1ZHkiKT4xKXt2YXIgZnJhbWVBcnJheT1kb2N1bWVudC5nZXRFbGVtZW50c0J5VGFnTmFtZSgiaWZyYW1lIilbMF0uY29udGVudFdpbmRvdy5kb2N1bWVudC5nZXRFbGVtZW50c0J5VGFnTmFtZSgiaWZyYW1lIik7Zm9yKGk9MDtmcmFtZUFycmF5W2ldO2krKyl7dmFyIHBsYXk9ZnJhbWVBcnJheVtpXS5jb250ZW50V2luZG93LkhUTUxNZWRpYUVsZW1lbnQucHJvdG90eXBlLnBsYXk7ZnJhbWVBcnJheVtpXS5jb250ZW50V2luZG93LkhUTUxNZWRpYUVsZW1lbnQucHJvdG90eXBlLnBsYXk9ZnVuY3Rpb24oKXt0aGlzLnBsYXliYWNrUmF0ZT0xNixwbGF5LmNhbGwodGhpcyl9fX0=");
Kiyomi.jsInjectPageFinished(injectJS);
var pipJS=Base64.decode("amF2YXNjcmlwdDpLaXlvbWkuanNFbnRlclBJUCgyLDEpOw==")
Kiyomi.jsInjectButton1(pipJS,"https://cdn.jsdelivr.net/gh/qinlili23333/KiyomiMethanol@main/OnlineMarket/ChaoXing/baseline_close_fullscreen_black_48dp.png")
document.location.href="https://i.mooc.chaoxing.com"
